### ISSUE TITLE
Improve functionality of the app

### ISSUE THREAD

**Issue by rahulsain** [rahulsain3000/LoginScreen#1]
This app is not working properly on clicking the "forgot password" and "register" button.

Any further improvement is most welcome.

Please read CONTRIBUTING.md before forking this project.

**Comment by Shiwanee** [comment]
@rahulsain3000 , I was looking for some documentation project. This one has the tag, but I could not see any relevant information in the description. Could you please elaborate on the documentation side of this project?

**Comment by rahulsain** [comment]
Hey @Shiwanee you could enhance the readme file, if you could. If you need more elaboration of this project. Please feel free to ask
